# Generated by Django 4.1 on 2023-01-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_familiares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='parentesco',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
